# Generated by Django 5.2.4 on 2025-07-08 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.AddField(
            model_name='customuser',
            name='channel_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_video',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_video'),
        ),
    ]
