# Generated by Django 5.2.4 on 2025-07-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_video_author_customuser_channel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
