# Generated by Django 5.2.4 on 2025-07-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_profile_pic_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='description',
        ),
    ]
