# Generated by Django 5.2.4 on 2025-07-10 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscription_videolike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='VideoLike',
        ),
    ]
