# Generated by Django 5.2.4 on 2025-07-10 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_videolike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
